language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "pypy"

before_install:
# Workaround for a permissions issue with Travis virtual machine images
# that breaks Python's multiprocessing:
# https://github.com/travis-ci/travis-cookbooks/issues/155
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm
 - pip install nose==1.3.0
 - pip install coverage==3.6

before_script:
 - python setup.py install

script:
 - nosetests -v --with-coverage --cover-package=<+module+> test
